notifications:
  email: false

# Quick boot options
sudo: false
cache:
  yarn: true
  directories:
    - ~/.npm
    - development/node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: DPuz6TcSDJwVmRuJB4hM4KRmYjAATy/pWgOD81TB5enmEVvWRIPyHIeB7zWxlAKISClOSYxijg63VgBM7zUtICa8uw9RGQCHb3jmNxpREXECrYFS0jbEb/fYCbdZy7Sx0Dsf2X2XD5fU53tBpjXI0UgP9i0bWC6v+4mqOJ0iFw8f7IE7TgV+BRVxkTKOE/Uw3r0pI2DbRWlcwBSAt4+9F+jS05vZkYxsVC/1SuRXlku+OlvO6kJ3ZKvplguzwMoAGJ6e7nZ1To4T5uZnJEAi0BXgtXaCwqhfmdJ9IxK0772CYYb3Wj7ftNJdCeDGium1fYGeDucA66SiUkklKt5CDCVJNKeE+OkP6jzYNaI7PLJgJAcv8Y7XiP6siGcBX/83FmaN4e5Yb7wx/CE0BhzB1OR8fNUc3fvaK9utHEBC0j8o7OPTnx8ISY9o8QEhheGd9lV8S2Ejm1t+1Lw8+qzRuIdmSfJ2spOm+GnYk23NyHPbxNvfF81grcg45DELezOq1fhvRAFJb5orTcrX6Oo3AhpkjMEgRZPUbsWztsGA4Eh+SBSNn//ArtUbXkhHO5sNb+s6n7dvGdcOBCrEio2y+Jj636XL6zDX0Xnxx+vR6sX2jvEi4Q2VDinGQruHOTS7utPXG8XALeubHDoFnlBl+9nFMYjcAxRDnN4BIYleEBo=

# Language options
language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8.2.1
install:
  - cd development
  - yarn install
script:
  - npm run cover
  - npm run lint

# Npm publish options
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: TXIZcgGv2AuooxP7MW9xRewkkVGgLAw/hHebDAGxq7+0op66S1UFiWWrcdlLIkWbtQS0KBBlHEFBS3i5sHDk2idKTv+DclfpZjGVNyy9cR+GfHCOPEozUMe/n3VkxO+w9cp4cZ8j4LIPMWCV/batSJcSs/c+mOc5ir6LaQgCZqpygfuwXzSjv2iS+oTN+vY18NBdXhnRTlEcfkuwVbXts3MAC2nAtgkvMm38FLsdbuKGbX1pE+NL89ycDgq0Nm70EM/ZNI39Dn405ysnqFnJ4SboliXsL3ihnjupNyRUmtNTyUJ2yYpjYR6C7qC27+J3SFGCNq4o/V4LR5sbq1VQkx2ADll4GXOR9V8qb11VULNOlJXRw8U+duoDkVAtUdja3T/jhNxmXMQIKFafFTCDFNvw8AtOpjmYjEAA7FlU7N5G34KM2UmiYTcXeSDqP7NNzLWd3seXMgY0fTOT2cSG0YtQlgApaZ4YUtSjtE/+W9Z/Ic27GJRBIBwiiDkVbrYJZneCDRhInCcPq6O3HB2fDwvkQnw6Azrco/1hXvRqZFST0qPAkOtntad3D5WlLVV9HWrXn3SDgI7cy4bfa8PbidTkHUAxaxwN8ygTYO+LdXVLEpwQIdnZag79rd7uOszVvBpvnNK6jggbcZE7ClozGqaww7BMQQn/Ki175YBWdpI=
  on:
    node: 8.2.1
